### ISSUE TITLE
commit-msg regex

### ISSUE THREAD

**Issue by BRO3886** [GDGVIT/template#29]
commit-msg regex is wrong pls check again

**Comment by saikun0293** [comment]
Hey, sorry for the late reply. Changing the regex to this
```
^Merge.+|(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|types)(\(.+\))?!?: [a-zA-Z0-9 ]+$
```

This good? @BRO3886

**Comment by saikun0293** [comment]
I'm updating the regex. Feel free to reopen the issue again incase anything is wrong
